### ISSUE TITLE
learning by debugging non-optimized code

### ISSUE THREAD

**Issue by datasmithtech** [mpetkov/ng2-finance#4]
Nice program.. I am interested in debugging your code to learn Angular better. How does one change the configuration so that the deployed bundle is not optimized so i can step thru using Chrome's developer's tools?

**Comment by TheILPlace** [comment]
this is an Angular-CLI project now. 
just do "ng serve" that will compile and load it with source maps, so you can see the TS code in the browser

**Comment by beinoriusju** [comment]
Yes, nice project here.
