### ISSUE TITLE
I there a way to use this as a module?

### ISSUE THREAD

**Issue by nassan** [mpetkov/ng2-finance#5]
I would like to include this as a module in my app.

And then somewhere in the HTML, simply write `<yahoo-finance></yahoo-finance>` and have this all load up within that tag. Is that possible?

**Comment by mpetkov** [comment]
I apologize for the late reply, for some reason I never saw this.  This app is not built to be used the way you described.  Also, the APIs used to get the stocks is not reliable and will not give accurate quotes.
